[package]
name = "dsim"
version = "0.3.0"
edition = "2024"
repository = "https://github.com/danthegoodman1/dsim"
license = "MIT"
description = "A deterministic simulation testing framework for Rust"

[dependencies]
flume = "0.11.1"

[dev-dependencies]
maplit = "1.0.2"
